export const LOGOUT_USER = "LOGOUT_USER";
export const DAY1_STEP_2_VALIDATIONS_FAILED = "DAY1_STEP_2_VALIDATIONS_FAILED";
export const GET_CENTER_INF_PV_CH = "GET_CENTER_INF_PV_CH";
export const GET_CENTER_INF_PV_CH_SUCCESS = "GET_CENTER_INF_PV_CH_SUCCESS";
export const GET_CENTER_INF_PV_CH_FAILED = "GET_CENTER_INF_PV_CH_FAILED";
export const UPDATE_CENTER_INF_PV_CH = "UPDATE_CENTER_INF_PV_CH";
export const UPDATE_CENTER_INF_PV_CH_SUCCESS = "UPDATE_CENTER_INF_PV_CH_SUCCESS";
export const UPDATE_CENTER_INF_PV_CH_FAILED = "UPDATE_CENTER_INF_PV_CH_FAILED";
export const GET_SCORE_PV_CH = "GET_SCORE_PV_CH";
export const GET_SCORE_PV_CH_SUCCESS = "GET_SCORE_PV_CH_SUCCESS";
export const GET_SCORE_PV_CH_FAILED = "GET_SCORE_PV_CH_FAILED";
export const GET_SCORE_GLOBAL_PV_CH = "GET_SCORE_GLOBAL_PV_CH";
export const GET_SCORE_GLOBAL_PV_CH_SUCCESS = "GET_SCORE_GLOBAL_PV_CH_SUCCESS";
export const GET_SCORE_GLOBAL_PV_CH_FAILED = "GET_SCORE_GLOBAL_PV_CH_FAILED";
export const CLOSE_DAY_PV_CH = "CLOSE_DAY_PV_CH";
export const CLOSE_DAY_CLEAR_PV_CH = "CLOSE_DAY_CLEAR_PV_CH";
export const GET_SCORE_GLOBAL_MODERATOR_PV_CH = "GET_SCORE_GLOBAL_MODERATOR_PV_CH";
export const GET_SCORE_GLOBAL_MODERATOR_PV_CH_SUCCESS = "GET_SCORE_GLOBAL_MODERATOR_PV_CH_SUCCESS";
export const GET_SCORE_GLOBAL_MODERATOR_PV_CH_FAILED = "GET_SCORE_GLOBAL_MODERATOR_PV_CH_FAILED";
export const ONCHANGE_RADIO = "ONCHANGE_RADIO";
export const DGD_DECISIONS = "DGD_DECISIONS";
export const VALIDATION_DAY = "VALIDATION_DAY";
export const VALIDATION_DAY_SUCCESS = "VALIDATION_DAY_SUCCESS";
export const CHANGE_SELECT_DECISIONS_FOLDER = "CHANGE_SELECT_DECISIONS_FOLDER";
export const CLEAR_DAY = "CLEAR_DAY";
export const CLEAR_ALL_DAY_DATA = "CLEAR_ALL_DAY_DATA";
export const DAY2_PART2_PV_CH_ONCHANGE_IS_SELECTED = "DAY2_PART2_PV_CH_ONCHANGE_IS_SELECTED";
export const DAY2_PV_CH_GET_DETAIL = "DAY2_PV_CH_GET_DETAIL";
export const DAY3_PART2_PV_CH_ONDRAG = "DAY3_PART2_PV_CH_ONDRAG";
export const DAY3_PV_CH_GET_DETAIL = "DAY3_PV_CH_GET_DETAIL";
export const DAY4_PV_CH_ONCHANGE_CAT2 = "DAY4_PV_CH_ONCHANGE_CAT2";
export const DAY4_PV_CH_ONCHANGE_CAT1 = "DAY4_PV_CH_ONCHANGE_CAT1";
export const DAY4_PV_CH_ONCHANGE_CAT3 = "DAY4_PV_CH_ONCHANGE_CAT3";
export const DAY4_PART2_PV_CH_CHANGE_IS_SELECTED_RADIO = "DAY4_PART2_PV_CH_CHANGE_IS_SELECTED_RADIO";
export const DAY4_PV_CH_GET_DETAIL = "DAY4_PV_CH_GET_DETAIL";
export const DAY5_PV_CH_GET_DETAIL = "DAY5_PV_CH_GET_DETAIL";
export const GET_SCORE5_PV_CH = "GET_SCORE5_PV_CH";
export const GET_SCORE5_PV_CH_SUCCESS = "GET_SCORE5_PV_CH_SUCCESS";
export const GET_SCORE5_PV_CH_FAILED = "GET_SCORE5_PV_CH_FAILED";
export const VALIDATE_ACTIVITY = "VALIDATE_ACTIVITY";
export const MOVE_MATRIX_DRD = "MOVE_MATRIX_DRD";
export const SET_MATRIX_STEP = "SET_MATRIX_STEP";
export const SET_CURRENT_AVATAR = "SET_CURRENT_AVATAR";

export const DAY_GET_DETAIL = "DAY_GET_DETAIL";
export const DAY_GET_DETAIL_SUCCESS = "DAY_GET_DETAIL_SUCCESS";
export const DAY_GET_DETAIL_FAILED = "DAY_GET_DETAIL_FAILED";




