export const LOGOUT_USER = "LOGOUT_USER";
export const DAY7_ON_CHANGE_CAS_OPTION = "DAY7_ON_CHANGE_CAS_OPTION";
export const DAY7_VALID_CAS = "DAY7_VALID_CAS";
export const DAY7_VALID_CAS_SUCCESS = "DAY7_VALID_CAS_SUCCESS";
export const DAY7_VALID_CAS_FAILED = "DAY7_VALID_CAS_FAILED";
export const DAY10_ON_CHANGE_PART1 = "DAY10_ON_CHANGE_PART1";
export const DAY10_ON_CHANGE_PART2 = "DAY10_ON_CHANGE_PART2";
export const DAY10_RESET_PART2 = "DAY10_RESET_PART2";
export const DAY5_ONSELECT_CAT = "DAY5_ONSELECT_CAT";
export const DAY5_ONCHANGE_CAT0_RANK1 = "DAY5_ONCHANGE_CAT0_RANK1";
export const DAY5_ONCHANGE_CAT0_RANK2 = "DAY5_ONCHANGE_CAT0_RANK2";
export const DAY5_ONCHANGE_CAT0_RANK3 = "DAY5_ONCHANGE_CAT0_RANK3";
export const DAY5_ONCHANGE_CAT0_RANK4 = "DAY5_ONCHANGE_CAT0_RANK4";
export const DAY5_ONCHANGE_CAT1_LEFT_DECISIONS1 = "DAY5_ONCHANGE_CAT1_LEFT_DECISIONS1";
export const DAY5_ONCHANGE_CAT1_LEFT_DECISIONS2 = "DAY5_ONCHANGE_CAT1_LEFT_DECISIONS2";
export const DAY5_ONCHANGE_CAT1_LEFT_DECISIONS3 = "DAY5_ONCHANGE_CAT1_LEFT_DECISIONS3";
export const DAY5_ONCHANGE_CAT1_LEFT_DECISIONS4 = "DAY5_ONCHANGE_CAT1_LEFT_DECISIONS4";
export const DAY5_ONCHANGE_CAT1_RIGHT_DECISIONS1 = "DAY5_ONCHANGE_CAT1_RIGHT_DECISIONS1";
export const DAY5_ONCHANGE_CAT1_RIGHT_DECISIONS2 = "DAY5_ONCHANGE_CAT1_RIGHT_DECISIONS2";
export const DAY5_ONCHANGE_CAT1_RIGHT_DECISIONS3 = "DAY5_ONCHANGE_CAT1_RIGHT_DECISIONS3";
export const DAY5_ONCHANGE_CAT1_RIGHT_DECISIONS4 = "DAY5_ONCHANGE_CAT1_RIGHT_DECISIONS4";
export const DAY5_ONCHANGE_CAT2_LEFT_DECISIONS1 = "DAY5_ONCHANGE_CAT2_LEFT_DECISIONS1";
export const DAY5_ONCHANGE_CAT2_LEFT_DECISIONS2 = "DAY5_ONCHANGE_CAT2_LEFT_DECISIONS2";
export const DAY5_ONCHANGE_CAT2_LEFT_DECISIONS3 = "DAY5_ONCHANGE_CAT2_LEFT_DECISIONS3";
export const DAY5_ONCHANGE_CAT2_LEFT_DECISIONS4 = "DAY5_ONCHANGE_CAT2_LEFT_DECISIONS4";
export const DAY5_ONCHANGE_CAT2_RIGHT_DECISIONS1 = "DAY5_ONCHANGE_CAT2_RIGHT_DECISIONS1";
export const DAY5_ONCHANGE_CAT2_RIGHT_DECISIONS2 = "DAY5_ONCHANGE_CAT2_RIGHT_DECISIONS2";
export const DAY5_ONCHANGE_CAT2_RIGHT_DECISIONS3 = "DAY5_ONCHANGE_CAT2_RIGHT_DECISIONS3";
export const DAY5_ONCHANGE_CAT2_RIGHT_DECISIONS4 = "DAY5_ONCHANGE_CAT2_RIGHT_DECISIONS4";
export const DAY5_ONCHANGE_CAT2_RANK1 = "DAY5_ONCHANGE_CAT2_RANK1";
export const DAY5_ONCHANGE_CAT2_RANK2 = "DAY5_ONCHANGE_CAT2_RANK2";
export const DAY5_ONCHANGE_CAT2_RANK3 = "DAY5_ONCHANGE_CAT2_RANK3";
export const DAY5_ONCHANGE_CAT2_RANK4 = "DAY5_ONCHANGE_CAT2_RANK4";
export const DAY5_VALIDATION = "DAY5_VALIDATION";
export const DAY5_VALIDATION_FAILED = "DAY5_VALIDATION_FAILED";
export const DAY5_VALIDATION_SUCCESS = "DAY5_VALIDATION_SUCCESS";
export const DAY8_VALIDATION = "DAY8_VALIDATION";
export const DAY8_VALIDATION_FAILED = "DAY8_VALIDATION_FAILED";
export const DAY8_VALIDATION_SUCCESS = "DAY8_VALIDATION_SUCCESS";
export const DAY10_VALIDATIONS = "DAY10_VALIDATIONS";
export const DAY10_VALIDATIONS_SUCCESS = "DAY10_VALIDATIONS_SUCCESS";
export const DAY10_VALIDATIONS_FAILED = "DAY10_VALIDATIONS_FAILED";
export const Day10_GET_DETAIL = "Day10_GET_DETAIL";
export const Day10_GET_DETAIL_SUCCESS = "Day10_GET_DETAIL_SUCCESS";
export const Day10_GET_DETAIL_FAILED = "Day10_GET_DETAIL_FAILED";
export const DAY7_VALID_DAY = "DAY7_VALID_DAY";
export const DAY7_VALID_DAY_SUCCESS = "DAY7_VALID_DAY_SUCCESS";
export const DAY7_VALID_DAY_FAILED = "DAY7_VALID_DAY_FAILED";
export const DAY7_GET_DETAIL = "DAY7_GET_DETAIL";
export const DAY7_GET_DETAIL_SUCCESS = "DAY7_GET_DETAIL_SUCCESS";
export const DAY7_GET_DETAIL_FAILED = "DAY7_GET_DETAIL_FAILED";
export const DAY1_PART2_ONDRAG = "DAY1_PART2_ONDRAG";
export const DAY1_PART1_ONCHANGE_IS_SELECTED = "DAY1_PART1_ONCHANGE_IS_SELECTED";
export const PH5_DAY5_PART1_ONCHANGE_IS_SELECTED = "PH5_DAY5_PART1_ONCHANGE_IS_SELECTED";
export const DAY1_VALIDATION = "DAY1_VALIDATION";
export const DAY1_VALIDATION_SUCCESS = "DAY1_VALIDATION_SUCCESS";
export const DAY1_VALIDATION_FAILED = "DAY1_VALIDATION_FAILED";
export const DAY1_GET_DETAIL = "DAY1_GET_DETAIL";
export const DAY1_GET_DETAIL_SUCCESS = "DAY1_GET_DETAIL_SUCCESS";
export const DAY1_GET_DETAIL_FAILED = "DAY1_GET_DETAIL_FAILED";
export const DAY1_STEP_2_VALIDATIONS = "DAY1_STEP_2_VALIDATIONS";
export const DAY1_STEP_2_VALIDATIONS_SUCCESS = "DAY1_STEP_2_VALIDATIONS_SUCCESS";
export const DAY1_STEP_2_VALIDATIONS_FAILED = "DAY1_STEP_2_VALIDATIONS_FAILED";
export const DAY1_STEP_2_GET_DETAIL = "DAY1_STEP_2_GET_DETAIL";
export const DAY1_STEP_2_GET_DETAIL_SUCCESS = "DAY1_STEP_2_GET_DETAIL_SUCCESS";
export const DAY1_STEP_2_GET_DETAIL_FAILED = "DAY1_STEP_2_GET_DETAIL_FAILED";
export const PVPHA_Day3_ONCHANGE_CAT3 = "PVPHA_Day3_ONCHANGE_CAT3";
export const PVPHA_Day3_ONCHANGE_CAT1 = "PVPHA_Day3_ONCHANGE_CAT1";
export const PVPHA_Day3_VALIDATION = "PVPHA_Day3_VALIDATION";
export const PVPHA_Day3_VALIDATION_SUCCESS = "PVPHA_Day3_VALIDATION_SUCCESS";
export const PVPHA_Day3_VALIDATION_FAILED = "PVPHA_Day3_VALIDATION_FAILED";
export const PVPHA_Day3_GET_DETAIL = "PVPHA_Day3_GET_DETAIL";
export const PVPHA_Day3_GET_DETAIL_SUCCESS = "PVPHA_Day3_GET_DETAIL_SUCCESS";
export const PVPHA_Day3_GET_DETAIL_FAILED = "PVPHA_Day3_GET_DETAIL_FAILED";
export const PH5_DAY2_GET_DETAIL = "PH5_DAY2_GET_DETAIL";
export const PH5_DAY2_VALID_DAY = "PH5_DAY2_VALID_DAY";
export const PH5_DAY2_VALID_DAY_FAILED = "PH5_DAY2_VALID_DAY_FAILED";
export const PH5_DAY2_VALID_DAY_SUCCESS = "PH5_DAY2_VALID_DAY_SUCCESS";
export const PH5_DAY2_Part1_ONCHANGE = "PH5_DAY2_Part1_ONCHANGE";
export const PH5_DAY2_PART2_ONDRAG = "PH5_DAY2_PART2_ONDRAG";
export const PH5_DAY2_PART3_ONCHANGE_IS_SELECTED = "PH5_DAY2_PART3_ONCHANGE_IS_SELECTED";
export const PH5_DAY3_PART2_ONCHANGE_IS_SELECTED = "PH5_DAY3_PART2_ONCHANGE_IS_SELECTED";

export const PH5_DAY4_PART1_ONCHANGE_IS_SELECTED = "PH5_DAY4_PART1_ONCHANGE_IS_SELECTED";
export const PH5_DAY4_PART2_ONCHANGE_IS_SELECTED = "PH5_DAY4_PART2_ONCHANGE_IS_SELECTED";
export const PH5_DAY4_PART3_ONCHANGE_IS_SELECTED = "PH5_DAY4_PART3_ONCHANGE_IS_SELECTED";
export const PH5_DAY4_STEP_4_UPDATE_DECISIONS = "PH5_DAY4_STEP_4_UPDATE_DECISIONS";
export const PH5_DAY4_VALIDATION = "PH5_DAY4_VALIDATION";
export const PH5_DAY4_VALIDATION_FAILED = "PH5_DAY4_VALIDATION_FAILED";
export const PH5_DAY4_VALIDATION_SUCCESS = "PH5_DAY4_VALIDATION_SUCCESS";

//  --------- pv challenge  --------------------------------


export const GET_CENTER_INF_PV_CH = "GET_CENTER_INF_PV_CH";
export const GET_CENTER_INF_PV_CH_SUCCESS = "GET_CENTER_INF_PV_CH_SUCCESS";
export const GET_CENTER_INF_PV_CH_FAILED = "GET_CENTER_INF_PV_CH_FAILED";
export const UPDATE_CENTER_INF_PV_CH = "UPDATE_CENTER_INF_PV_CH";
export const UPDATE_CENTER_INF_PV_CH_SUCCESS = "UPDATE_CENTER_INF_PV_CH_SUCCESS";
export const UPDATE_CENTER_INF_PV_CH_FAILED = "UPDATE_CENTER_INF_PV_CH_FAILED";
export const GET_SCORE_PV_CH = "GET_SCORE_PV_CH";
export const GET_SCORE_PV_CH_SUCCESS = "GET_SCORE_PV_CH_SUCCESS";
export const GET_SCORE_PV_CH_FAILED = "GET_SCORE_PV_CH_FAILED";
export const GET_SCORE_GLOBAL_PV_CH = "GET_SCORE_GLOBAL_PV_CH";
export const GET_SCORE_GLOBAL_PV_CH_SUCCESS = "GET_SCORE_GLOBAL_PV_CH_SUCCESS";
export const GET_SCORE_GLOBAL_PV_CH_FAILED = "GET_SCORE_GLOBAL_PV_CH_FAILED";
export const CLOSE_DAY_PV_CH = "CLOSE_DAY_PV_CH";
export const CLOSE_DAY_CLEAR_PV_CH = "CLOSE_DAY_CLEAR_PV_CH";
export const GET_SCORE_GLOBAL_MODERATOR_PV_CH = "GET_SCORE_GLOBAL_MODERATOR_PV_CH";
export const GET_SCORE_GLOBAL_MODERATOR_PV_CH_SUCCESS = "GET_SCORE_GLOBAL_MODERATOR_PV_CH_SUCCESS";
export const GET_SCORE_GLOBAL_MODERATOR_PV_CH_FAILED = "GET_SCORE_GLOBAL_MODERATOR_PV_CH_FAILED";


export const ONCHANGE_RADIO = "ONCHANGE_RADIO";

export const DGD_DECISIONS = "DGD_DECISIONS";

export const VALIDATION_DAY = "VALIDATION_DAY";
export const VALIDATION_DAY_SUCCESS = "VALIDATION_DAY_SUCCESS";
export const CHANGE_SELECT_DECISIONS_FOLDER  = "CHANGE_SELECT_DECISIONS_FOLDER";

export const CLEAR_DAY  = "CLEAR_DAY";

export const CLEAR_ALL_DAY_DATA  = "CLEAR_ALL_DAY_DATA";


// -------------------------day1---------------------------------------

export const DAY1_PART3_ONCHANGE_PV_CH = "DAY1_PART3_ONCHANGE_PV_CH";
export const DAY1_VALIDATION_PV_CH = "DAY1_VALIDATION_PV_CH";


// -------------------------day2---------------------------------------
export const DAY2_PART2_PV_CH_ONCHANGE_IS_SELECTED = "DAY2_PART2_PV_CH_ONCHANGE_IS_SELECTED";
export const DAY2_PART1_PV_CH_ONCHANGE_IS_SELECTED = "DAY2_PART1_PV_CH_ONCHANGE_IS_SELECTED";
export const DAY2_PART4_PV_CH_ONCHANGE_IS_SELECTED = "DAY2_PART4_PV_CH_ONCHANGE_IS_SELECTED";
export const DAY2_VALID_DAY_PV_CH = "DAY2_VALID_DAY_PV_CH";
export const DAY2_PV_CH_GET_DETAIL = "DAY2_PV_CH_GET_DETAIL";
export const DAY2_GET_PV_CH_DETAIL_SUCCESS = "DAY2_GET_PV_CH_DETAIL_SUCCESS";
export const DAY2_GET_PV_CH_DETAIL_FAILED = "DAY2_GET_PV_CH_DETAIL_FAILED";

// ------------------------day 3----------------------------------------

export const DAY3_PART1_PV_CH_ONCHANGE_IS_SELECTED = "DAY3_PART1_PV_CH_ONCHANGE_IS_SELECTED";
export const DAY3_PART1_ONCHANGE_PV_CH = "DAY3_PART1_ONCHANGE_PV_CH";
export const DAY3_PART2_PV_CH_ONDRAG = "DAY3_PART2_PV_CH_ONDRAG";
export const DAY3_PART3_PV_CH_ONCHANGE_IS_SELECTED = "DAY3_PART3_PV_CH_ONCHANGE_IS_SELECTED";
export const DAY3_PART4_ONCHANGE_PV_CH = "DAY3_PART4_ONCHANGE_PV_CH";
export const DAY3_PART5_PV_CH_ONCHANGE_IS_SELECTED = "DAY3_PART5_PV_CH_ONCHANGE_IS_SELECTED";
export const DAY3_VALIDATION_PV_CH = "DAY3_VALIDATION_PV_CH";
export const DAY3_PV_CH_GET_DETAIL = "DAY3_PV_CH_GET_DETAIL";
export const DAY3_GET_PV_CH_DETAIL_SUCCESS = "DAY3_GET_PV_CH_DETAIL_SUCCESS";
export const DAY3_GET_PV_CH_DETAIL_FAILED = "DAY3_GET_PV_CH_DETAIL_FAILED";


// ----------------------------day 4------------------------------------

export const DAY4_PV_CH_ONCHANGE_CAT2 = "DAY4_PV_CH_ONCHANGE_CAT2";
export const DAY4_PV_CH_ONCHANGE_CAT1 = "DAY4_PV_CH_ONCHANGE_CAT1";
export const DAY4_PV_CH_ONCHANGE_CAT3 = "DAY4_PV_CH_ONCHANGE_CAT3";

export const DAY4_PART2_PV_CH_CHANGE_IS_SELECTED_RADIO = "DAY4_PART2_PV_CH_CHANGE_IS_SELECTED_RADIO";
export const DAY4_VALIDATION_PV_CH = "DAY4_VALIDATION_PV_CH";
export const DAY4_PV_CH_GET_DETAIL = "DAY4_PV_CH_GET_DETAIL";
export const DAY4_PV_CH_GET_DETAIL_SUCCESS = "DAY4_PV_CH_GET_DETAIL_SUCCESS";
export const DAY4_PV_CH_GET_DETAIL_FAILED = "DAY4_PV_CH_GET_DETAIL_FAILED";
export const DAY5_PV_CH_GET_DETAIL = "DAY5_PV_CH_GET_DETAIL";
export const DAY5_PV_CH_GET_DETAIL_SUCCESS = "DAY5_PV_CH_GET_DETAIL_SUCCESS";
export const DAY5_PV_CH_GET_DETAIL_FAILED = "DAY5_PV_CH_GET_DETAIL_FAILED";
export const GET_SCORE5_PV_CH = "GET_SCORE5_PV_CH";
export const GET_SCORE5_PV_CH_SUCCESS = "GET_SCORE5_PV_CH_SUCCESS";
export const GET_SCORE5_PV_CH_FAILED = "GET_SCORE5_PV_CH_FAILED";
export const GET_SCORE_PV_CH_GLOBAL = "GET_SCORE_PV_CH_GLOBAL";





